name: Build Browser Extension

on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  publish:
    name: Build Extension
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build Chrome extension
        run: npm run build

      - name: Build Firefox extension
        run: npm run build:firefox

      - name: Zip Chrome folder
        run: |
          cd dist
          zip -r chrome.zip chrome/

      - name: Zip Firefox folder
        run: |
          cd dist
          zip -r firefox.zip firefox/

      - name: Get manifest version
        id: manifest_version
        run: |
          version=$(cat manifest.json | jq -r .version)
          echo "::set-output name=version::$version"

      - name: Get short commit hash
        id: commit_hash
        run: |
          short_hash=$(git rev-parse --short HEAD)
          echo "::set-output name=short_hash::$short_hash"

      - name: Upload build asset
        uses: actions/upload-artifact@v4
        with:
          name: v${{ steps.manifest_version.outputs.version }}-${{ steps.commit_hash.outputs.short_hash }}
          path: dist/*.zip

      - name: Remove dist folder
        run: rm -rf dist
